### PR TITLE
Feature/store-locator

### PR DESCRIPTION
**Pull request by LeonardMeagher2**
- Start using prettier-eslint so prettir respects our eslint rules
- Use eslint-plugin-react to help style jsx code
- Use eslint-plugin-jsx-a11y for enforcing accessibility (strict version)
- eslint-plugin-markdown to properly style markdown
**Check .eslintrc.json for exact config**

- Setup styleguidist and use that to take over our sandbox
- Start using async reducers, and a service pattern documented in /src/README.md
- Add LocationField component
- Add @google/maps + make it a service for components
- Add slt-stores as a service to Sur La Tables store api (Don't include endpoint or api key in source)
- Make Store and StoreProvider global
- Add DotEnv to allow testing api keys in docs
- Add axios for http requests and store2 for local and session storage

### CODE REVIEW

**Comment by LeonardMeagher2** [comment]
@ryanpcmcquen 
Fixed the typo, but you're welcome to change the react styleguidist info to your personal preference in another PR.
Also CodeSandbox doesn't work as far as I know, so it doesn't make much sense to have in the readme.

**Comment by ryanpcmcquen** [comment]
@LeonardMeagher2, this doesn't work for you?
https://codesandbox.io/s/github/SurLaTable/slt-ui/tree/0b63e06d14b42cc5f91739dff90a09ed747b1e93

**Comment by LeonardMeagher2** [comment]
@ryanpcmcquen That's a specific commit and doesn't work if you change it to develop, and the statement `Conversely, you can also hack on components using CodeSandbox`  implies you get to work on update to date components which isn't true.

**Comment by LeonardMeagher2** [comment]
Also @ryanpcmcquen

**Comment by ryanpcmcquen** [comment]
We should reword that verbiage, but the value of having an instantly clickable view into the ecosystem is a great way to show people what we are doing, and it will be updated soon enough.

**Comment by LeonardMeagher2** [comment]
@ryanpcmcquen I don't think as a developer (who is also our user) an outdated version of a library isn't very useful, the link is commented out not deleted, so if support for codesandbox gets better it's easy to uncomment. At the moment the link is misleading, and useless for actual understanding and development.

**Comment by ryanpcmcquen** [comment]
I guess I see it as destructive, since we are removing something that appears for the end user. It's not ideal, but it also isn't a complete misrepresentation of our library.

**Comment by ryanpcmcquen** [comment]
I think the key thing to consider here, is whether or not the decision to remove this link belongs in a branch for the Store Locator component.

**Comment by ryanpcmcquen** [comment]
@terryfritschSLT, can we get your eyes on this PR? I've fixed a few of the docs issues and I think it is ready to merge, although it does not represent a complete Store Locator component, it does include the changes mentioned in @LeonardMeagher2's original comment.

**Pull request merged**
