### PR TITLE
Fix docs for Linux & Unix systems. Begin adding static version of docs.

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
Also removed some dead code.

This fixes:
https://github.com/SurLaTable/slt-ui/pull/43#discussion_r212666283
https://github.com/SurLaTable/slt-ui/issues/20

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
@terryfritschSLT & @LeonardMeagher2, can we merge this before #43?

**Comment by LeonardMeagher2** [comment]
@terryfritschSLT I'd like to review this before it's merged

**Comment by ryanpcmcquen** [comment]
@LeonardMeagher2, thanks for fixing up the task commands, the only thing we are missing now is that the CSS file cannot be found (`styleguidist-env.css`) ... where should we be storing that so that the docs can access it?

**Comment by ryanpcmcquen** [comment]
@LeonardMeagher2, the custom CSS now loads, but it is also pulling in other files from our build folder. Is there a way to avoid this and still have the `styleguidist-env.css` load?

**Pull request merged**
